### ISSUE TITLE
Add resourceTransaction Method for gifting

### ISSUE THREAD

**Issue by Eirikalb** [SOMAS2020/SOMAS2020#110]
uint I guess

on the note of the transfer impl. -- the server acts as a middle man? The server would call a "GetGifts" function that returns a list of GiftInfo to other clients.

"ReceiveGift" is good to record who has given the island a gift.

If you want to pass the client pointers around to the other clients that's fine with me--there's two risks:

1. Malicious clients may call functions intended for the server and become an impostor. This can be solved by passing in only an implementation reserved for Inter-client functions. However this is not fool-proof: clients can cast this interface to any type. I'm fine with this, however, if it makes life much easier.
2. No caller identification. Say Team1 has access to Team2's pointer. How does Team2 know Team1 called that function? Trust? An implementation of MPC that would probably be worth the workload of a year-long project?

**Comment by QFSW** [comment]
> However this is not fool-proof: clients can cast this interface to any type

I'm completely fine with this for 2 main reasons

1. Anyone doing this would be _explicitly_ trying to cheat. We assume that clients are malicious, because out of programmer error, they may be so. I don't think however, that we should assume programmers are malicious. This whole project only works if we're cooperating, people can purposefully mess with the simulation in lots of other easier ways if they really want to.
2. A dynamic cast of that nature is poor code form anyway, and we ought to be rejecting it in PR (unless there is a good reason otherwise), regardless of whether the cast is malicious or not

**Comment by Eirikalb** [comment]
Yeah I think that this implementation makes sense too, I dont think people will intentionally try to hack into the server. This also allows for cheating, as `GetGifts` could return a list that does not equal the gifts actually offered in the gifting session

**Comment by lhl2617** [comment]
any updates or is this actually resolved?

**Comment by Eirikalb** [comment]
I think this actually might be resolved already
