### ISSUE TITLE
[INFRA/CORE] Fix protected folder check 

### ISSUE THREAD

**Issue by lhl2617** [SOMAS2020/SOMAS2020#16]
`.github/workflows/protected_folder.yml` currently only echos and shows that the test passes on PR.

It would be nice to have a warning (although this is not possible) if protected folders (i.e. non-client-side code) are changed.

This should be possible via comments.

**Comment by lhl2617** [comment]
@Darrekt  feel free to pick up

**Comment by QFSW** [comment]
So I did a bit of digging on this, I found an action that should be able to leave a comment on a PR
https://github.com/unsplash/comment-on-pr

It uses a secret token for the posting. Unfortunately, secrets aren't available to PRs triggered by forks, which would render it useless. I did find this however which _could_ be promising

https://github.com/marketplace/actions/github-action-comment-pull-request
Because of this in specific
```
You can use the default ${{ secret.GITHUB_TOKEN }} to tag the message with the github-actions bot .
```
Which might mean we don't need to setup any secrets for it, which would make it work

**Comment by lhl2617** [comment]
@QFSW  I'd say try it and see what happens? we can try from our team's fork

**Comment by QFSW** [comment]
For anyone who want's to fix this
 - It used to work but V2 broke it, so the new trigger (either file trigger or new branch trigger) is broken
 - doesn't work on fork PRs

**Comment by QFSW** [comment]
Fixed first issue, second is still present

**Comment by lhl2617** [comment]
tested on this repo and from a fork--working!

**Comment by QFSW** [comment]
This has now been resolved
