### ISSUE TITLE
IIGO never runs due to lack of funds

### ISSUE THREAD

**Issue by mpardalos** [SOMAS2020/SOMAS2020#166]
IIGO runs only if there is resources in the common pool to pay the officials. But the common pool only gets resources from taxes, which are set *by the officials that are not being paid*. So IIGO never has a chance to run.

Possible fixes:
* Have an initial amount in the common pool
* Broadcast an initial tax amount at the start
* Hardcode our agents to pay some tax on the first round, even though there is no tax policy
* Let officials choose whether they want to fulfill their role, even if they have not been paid, so that the first IIGO can run for free

**Comment by Neelesh99** [comment]
This is something being actively worked on for post-MVP IIGO, we will hopefully be able to allow Islands to us their own salaries to pay for their IIGO commitments if the common pool is lacking @Spruudis might be able to better shed some light on this?

**Comment by Spruudis** [comment]
We are working on this yes, it is taking some time though because as it turns out (surprise, surprise) a budget and having actions cost resources from the CP is really integral to the whole operation of IIGO and slightly touches almost every part and we want to make sure it actually functions as intended before we PR it out to you guys xd

**Comment by ezgimez** [comment]
oh god, help us about this situation. hopefully the _permission_ and _obligation_ difference will kinda solve this problem in terms of sanctions

**Comment by preetl** [comment]
I believe this is now resolved as @Neelesh99 has set the default initial common pool to 1000
