### ISSUE TITLE
[IIGO] Use of errors as return types

### ISSUE THREAD

**Issue by Neelesh99** [SOMAS2020/SOMAS2020#260]
PR #208 has moved a lot of IIGO return types to errors. We moved a lot of these away from errors during the end of MVP to ensure that we weren't just using errors as a data structure, most of these newly returned errors aren't logged or passed through. It seems a little like we are undoing some of the good work we did earlier, can we move back to named boolean returns.

**Comment by ezgimez** [comment]
RIP my sanity xx

**Comment by lhl2617** [comment]
CC authors @akowal3 @tobhil98

**Comment by tobhil98** [comment]
We converted them back to errors as from our understanding of the design, insufficient funds in the common pool should be treated as an error by IIGO and terminate the current session.

**Comment by Neelesh99** [comment]
That's fair, but could we not use a boolean to signal that, especially because the returned error is checked for nilness and then thrown away. If this is the only function of this error I think it would be better if we move it to boolean. Same for appointing new roles and the changes to Monitoring which now requires refactoring away from booleans to errors if the current return types are kept.

**Comment by tobhil98** [comment]
Originally we were returning the error from IIGO so that it could be handled by the server. We had a merge conflict with that so I patched it quickly by returning a string instead where needed. Another reason for choosing to return errors rather than bools was for example the replyAllocationRequest function which would then return a tuple of two booleans making it unclear exactly what each bool meant.
We could look into converting them to booleans, but at the moment we are trying to get the rules in before this evening.

**Comment by Neelesh99** [comment]
Fair enough, the rules are deffo the priority. Please do keep this in mind though. I guess we will need to refactor monitoring for now then.

**Comment by lhl2617** [comment]
closing. feature freezed
